USE Academia;
GO

CREATE TABLE Professor(
    ID_PROFESSOR INT IDENTITY(1,1) NOT NULL,
    NOME_PROFESSOR NVARCHAR(50) NOT NULL,
    ENDERECO_PROFESSOR NVARCHAR(50) NOT NULL,
    NUMERO_PROFESSOR NVARCHAR(10) NOT NULL,
    BAIRRO_PROFESSOR NVARCHAR(50) NOT NULL,
    CIDADE_PROFESSOR NVARCHAR(50) NOT NULL,
    CEP_PROFESSOR NVARCHAR(10) NOT NULL,
    CPF_PROFESSOR NVARCHAR(14) NOT NULL,
    SALARIO DECIMAL(7,2) NOT NULL,
    TELEFONE_PROFESSOR NVARCHAR(15) NOT NULL,
    OBSERVACAO NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_Professor PRIMARY KEY (ID_PROFESSOR)
);

CREATE TABLE Modalidade(
    ID_MODALIDADE INT IDENTITY(1,1) NOT NULL,
    NOME_MODALIDADE NVARCHAR(50) NOT NULL,
    MENSALIDADE DECIMAL(6,2) NOT NULL,
    ID_PROFESSOR INT NOT NULL,
    CONSTRAINT PK_Modalidade PRIMARY KEY (ID_MODALIDADE)
);

CREATE TABLE Turma(
    ID_TURMA INT IDENTITY(1,1) NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    MAXIMO_ALUNOS INT NOT NULL,
    NUMERO_TURMA INT NOT NULL,
    CONSTRAINT PK_Turma PRIMARY KEY (ID_TURMA)
);

CREATE TABLE Horario(
    ID_HORARIO INT IDENTITY(1,1) NOT NULL,
    ID_TURMA INT NOT NULL,
    DIA_SEMANA TINYINT NOT NULL,
    INICIO TIME NOT NULL,
    FIM TIME NOT NULL,
    CONSTRAINT PK_Horario PRIMARY KEY (ID_HORARIO)
);

CREATE TABLE Aluno(
    ID_ALUNO INT IDENTITY(1,1) NOT NULL,
    NOME_ALUNO NVARCHAR(50) NOT NULL,
    ENDERECO_ALUNO NVARCHAR(50) NOT NULL,
    BAIRRO_ALUNO NVARCHAR(50) NOT NULL,
    NUMERO_ALUNO NVARCHAR(10) NOT NULL,
    CIDADE_ALUNO NVARCHAR(50) NOT NULL,
    CEP_ALUNO NVARCHAR(10) NOT NULL,
    CPF_ALUNO NVARCHAR(14) NOT NULL,
    TELEFONE_ALUNO NVARCHAR(15) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    OBSERVACAO NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_Aluno PRIMARY KEY (ID_ALUNO)
);

CREATE TABLE Matricula(
    ID_MATRICULA INT IDENTITY(1,1) NOT NULL,
    ID_ALUNO INT NOT NULL,
    ID_TURMA INT NOT NULL,
    VENCIMENTO DATE NOT NULL,
    SITUACAO BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_Matricula PRIMARY KEY (ID_MATRICULA)
);

CREATE TABLE Mensalidade(
    ID_MENSALIDADE INT IDENTITY(1,1) NOT NULL,
    ID_MATRICULA INT NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    SITUACAO BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_Mensalidade PRIMARY KEY (ID_MENSALIDADE)
);

CREATE TABLE Caixa(
    ID_CAIXA INT IDENTITY(1,1) NOT NULL,
    DIA DATE NOT NULL,
    HORA TIME(0) NOT NULL,
    SALDO_INICIAL DECIMAL(12,2) NOT NULL,
    SITUACAO BIT NOT NULL,
    CONSTRAINT PK_Caixa PRIMARY KEY (ID_CAIXA)
);

CREATE TABLE Transacao_Caixa(
    ID_TRANSACAO INT IDENTITY(1,1) NOT NULL,
    ID_CAIXA INT NOT NULL,
    VALOR DECIMAL(12,2) NOT NULL,
    MOVIMENTO CHAR(1) NOT NULL,
    TIPO_PAGAMENTO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_Transacao PRIMARY KEY (ID_TRANSACAO)
);