-- Cria as tabelas do banco

USE Academia2;
GO

CREATE TABLE Professor(
    ID_PROFESSOR INT IDENTITY(1,1) NOT NULL,
    NOME_PROFESSOR NVARCHAR(50) NOT NULL,
    ENDERECO_PROFESSOR NVARCHAR(50) NOT NULL,
    NUMERO_PROFESSOR NVARCHAR(10) NOT NULL,
    BAIRRO_PROFESSOR NVARCHAR(50) NOT NULL,
    CIDADE_PROFESSOR NVARCHAR(50) NOT NULL,
    CEP_PROFESSOR NVARCHAR(10) NOT NULL,
    CPF_PROFESSOR NVARCHAR(14) NOT NULL,
    SALARIO DECIMAL(7,2) NOT NULL,
    TELEFONE_PROFESSOR NVARCHAR(15) NOT NULL,
    OBSERVACAO NVARCHAR(50),

    CONSTRAINT PK_Professor PRIMARY KEY (ID_PROFESSOR)
);

CREATE TABLE Modalidade(
    ID_MODALIDADE INT IDENTITY(1,1) NOT NULL,
	ID_PROFESSOR INT NOT NULL,
    NOME_MODALIDADE NVARCHAR(50) NOT NULL,
    MENSALIDADE DECIMAL(6,2) NOT NULL,   

    CONSTRAINT PK_Modalidade PRIMARY KEY (ID_MODALIDADE),
	CONSTRAINT FK_Modalidade_Professor FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID_PROFESSOR)
);

CREATE TABLE Turma(
    ID_TURMA INT IDENTITY(1,1) NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    MAXIMO_ALUNOS INT NOT NULL,
    NUMERO_TURMA INT NOT NULL,

    CONSTRAINT PK_Turma PRIMARY KEY (ID_TURMA),
	CONSTRAINT FK_Turma_Modalidade FOREIGN KEY (ID_MODALIDADE) REFERENCES Modalidade(ID_MODALIDADE)
);

CREATE TABLE Horario(
    ID_HORARIO INT IDENTITY(1,1) NOT NULL,
    ID_TURMA INT NOT NULL,
    DIA_SEMANA TINYINT NOT NULL,
    INICIO TIME(0) NOT NULL,
    FIM TIME(0) NOT NULL,

    CONSTRAINT PK_Horario PRIMARY KEY (ID_HORARIO),
	CONSTRAINT FK_Horario_Turma FOREIGN KEY (ID_TURMA) REFERENCES Turma(ID_TURMA)
);

CREATE TABLE Aluno(
    ID_ALUNO INT IDENTITY(1,1) NOT NULL,
    NOME_ALUNO NVARCHAR(50) NOT NULL,
    ENDERECO_ALUNO NVARCHAR(50) NOT NULL,
    BAIRRO_ALUNO NVARCHAR(50) NOT NULL,
    NUMERO_ALUNO NVARCHAR(10) NOT NULL,
    CIDADE_ALUNO NVARCHAR(50) NOT NULL,
    CEP_ALUNO NVARCHAR(10) NOT NULL,
    CPF_ALUNO NVARCHAR(14) NOT NULL,
    TELEFONE_ALUNO NVARCHAR(15) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    OBSERVACAO NVARCHAR(50),

    CONSTRAINT PK_Aluno PRIMARY KEY (ID_ALUNO)
);

CREATE TABLE Matricula(
    ID_MATRICULA INT IDENTITY(1,1) NOT NULL,
    ID_ALUNO INT NOT NULL,
    ID_TURMA INT NOT NULL,
    VENCIMENTO DATE NOT NULL,
    SITUACAO BIT NOT NULL DEFAULT 1,

    CONSTRAINT PK_Matricula PRIMARY KEY (ID_MATRICULA),
	CONSTRAINT FK_Matricula_Aluno FOREIGN KEY (ID_ALUNO) REFERENCES Aluno(ID_ALUNO),
	CONSTRAINT FK_Matricula_Turma FOREIGN KEY (ID_TURMA) REFERENCES Turma(ID_TURMA)
);

CREATE TABLE Mensalidade(
    ID_MENSALIDADE INT IDENTITY(1,1) NOT NULL,
    ID_MATRICULA INT NOT NULL,
	VALOR DECIMAL(12,2) NOT NULL,
	DATA_VENCIMENTO DATETIME NOT NULL,
    DATA_PAGAMENTO DATETIME,
	SITUACAO TINYINT NOT NULL,

    CONSTRAINT PK_Mensalidade PRIMARY KEY (ID_MENSALIDADE),
	CONSTRAINT FK_Mensalidade_Matricula FOREIGN KEY (ID_MATRICULA) REFERENCES Matricula(ID_MATRICULA),
	CONSTRAINT UQ_MENSALIDADE UNIQUE (ID_MATRICULA, DATA_VENCIMENTO),
	CONSTRAINT CK_Mensalidade_Situacao CHECK (SITUACAO IN (0, 1, 2))
	/*
	0 = EM ABERTO ou ATRASADA
	1 = PAGA
	2 = CANCELADA
	*/
);

CREATE TABLE Caixa(
    ID_CAIXA INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
    ATIVO BIT NOT NULL,

    CONSTRAINT PK_Caixa PRIMARY KEY (ID_CAIXA)
);

CREATE TABLE Abertura_Caixa(
	ID_ABERTURA INT IDENTITY(1,1) NOT NULL,
	ID_CAIXA INT NOT NULL,
	DATA_ABERTURA DATETIME NOT NULL,
	DATA_FECHAMENTO DATETIME,
	SALDO_INICIAL DECIMAL(12,2) NOT NULL,
	SALDO_FINAL_SISTEMA DECIMAL(12,2),
	SALDO_FINAL_INFORMADO DECIMAL(12,2),
	DIFERENCA DECIMAL(12,2),
	SITUACAO BIT NOT NULL,
	OBSERVACAO NVARCHAR(100),

	CONSTRAINT PK_Abertura PRIMARY KEY (ID_ABERTURA),
	CONSTRAINT FK_Abertura_Caixa FOREIGN KEY (ID_CAIXA) REFERENCES Caixa(ID_CAIXA)
);

CREATE TABLE Transacao_Caixa(
    ID_TRANSACAO INT IDENTITY(1,1) NOT NULL,
    ID_ABERTURA INT NOT NULL,
    VALOR DECIMAL(12,2) NOT NULL,
    MOVIMENTO CHAR(1) NOT NULL,
	TIPO_MOVIMENTO VARCHAR(20) NOT NULL,
    TIPO_PAGAMENTO VARCHAR(20) NOT NULL,
	DATA_HORA DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_Transacao PRIMARY KEY (ID_TRANSACAO),
	CONSTRAINT FK_Transacao_Abertura FOREIGN KEY (ID_ABERTURA) REFERENCES Abertura_Caixa(ID_ABERTURA),
	CONSTRAINT CK_Transacao_Movimentom CHECK (MOVIMENTO IN ('E', 'S')),	
	CONSTRAINT CK_TipoPagamento_Maiusculo CHECK (TIPO_PAGAMENTO = UPPER(TIPO_PAGAMENTO)),
	CONSTRAINT CK_Transacao_TipoPagamento CHECK (TIPO_PAGAMENTO IN ('DINHEIRO', 'PIX', 'CARTAO')),	
	CONSTRAINT CK_Valor_Positivo CHECK (VALOR > 0),
	CONSTRAINT CK_TipoMovimento CHECK (TIPO_MOVIMENTO IN ('SUPRIMENTO', 'RETIRADA', 'PAGAMENTO')),
);

CREATE TABLE Configuracoes(
	ID_CONFIG INT IDENTITY(1,1) NOT NULL,
	CHAVE VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	VALOR VARCHAR(255) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,

	CONSTRAINT PK_Configuracoes PRIMARY KEY (ID_CONFIG),
	CONSTRAINT UQ_CONFIG_CHAVE UNIQUE (CHAVE)
);

IF NOT EXISTS (
    SELECT 1 FROM Configuracoes WHERE CHAVE = 'GERAR_AUTO_MENSALIDADE'
)
BEGIN
    INSERT INTO Configuracoes (CHAVE, DESCRICAO, VALOR, TIPO)
    VALUES ('GERAR_AUTO_MENSALIDADE', 'Gerar mensalidade automaticamente', 'false', 'BOOL')
END