USE Academia;
GO

ALTER TABLE Modalidade
ADD CONSTRAINT FK_Modalidade_Professor
FOREIGN KEY (ID_PROFESSOR)
REFERENCES Professor(ID_PROFESSOR);

ALTER TABLE Turma
ADD CONSTRAINT FK_Turma_Modalidade
FOREIGN KEY (ID_MODALIDADE)
REFERENCES Modalidade(ID_MODALIDADE);

ALTER TABLE Horario
ADD CONSTRAINT FK_Horario_Turma
FOREIGN KEY (ID_TURMA)
REFERENCES Turma(ID_TURMA);

ALTER TABLE Matricula
ADD CONSTRAINT FK_Matricula_Aluno
FOREIGN KEY (ID_ALUNO)
REFERENCES Aluno(ID_ALUNO);

ALTER TABLE Matricula
ADD CONSTRAINT FK_Matricula_Turma
FOREIGN KEY (ID_TURMA)
REFERENCES Turma(ID_TURMA);

ALTER TABLE Mensalidade
ADD CONSTRAINT FK_Mensalidade_Matricula
FOREIGN KEY (ID_MATRICULA)
REFERENCES Matricula(ID_MATRICULA);

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT FK_Transacao_Caixa
FOREIGN KEY (ID_CAIXA)
REFERENCES Caixa(ID_CAIXA);

-- CHECKS
ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_Transacao_Movimento
CHECK (MOVIMENTO IN ('E', 'S'));

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_Transacao_TipoPagamento
CHECK (TIPO_PAGAMENTO IN ('DINHEIRO', 'PIX', 'CARTAO'));

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_Valor_Positivo
CHECK (VALOR > 0);

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_TipoPagamento_Maiusculo
CHECK (TIPO_PAGAMENTO = UPPER(TIPO_PAGAMENTO));

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_Movimento_Maiusculo
CHECK (MOVIMENTO = UPPER(MOVIMENTO));

ALTER TABLE Mensalidade
ADD CONSTRAINT CK_Mensalidade_Situacao
CHECK (SITUACAO IN (0, 1, 2));