USE Academia
GO

ALTER TABLE Transacao_Caixa
ADD DATA_TRANSACAO DATETIME;

UPDATE Transacao_Caixa
SET DATA_TRANSACAO = GETDATE()
WHERE DATA_TRANSACAO IS NULL;

ALTER TABLE Transacao_Caixa
ALTER COLUMN DATA_TRANSACAO DATETIME NOT NULL;

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT DF_TransacaoCaixa_Data
DEFAULT GETDATE() FOR DATA_TRANSACAO;