USE Academia
GO

ALTER TABLE Transacao_Caixa
ADD TIPO_MOVIMENTO VARCHAR(20);

UPDATE Transacao_Caixa
SET TIPO_MOVIMENTO = 
	CASE 
		WHEN MOVIMENTO = 'E' THEN 'SUPRIMENTO'
		ELSE 'RETIRADA'
	END
WHERE TIPO_MOVIMENTO IS NULL;

SELECT DISTINCT TIPO_MOVIMENTO FROM Transacao_Caixa;

ALTER TABLE Transacao_Caixa
ALTER COLUMN TIPO_MOVIMENTO VARCHAR(20) NOT NULL;

ALTER TABLE Transacao_Caixa
ADD CONSTRAINT CK_TipoMovimento
CHECK (TIPO_MOVIMENTO IN ('SUPRIMENTO', 'RETIRADA', 'PAGAMENTO'));