USE Academia
GO

ALTER TABLE Mensalidade
ADD VALOR DECIMAL(10,2);

UPDATE men
SET VALOR = md.MENSALIDADE
OUTPUT DELETED.*, INSERTED.*
FROM Mensalidade men
INNER JOIN Matricula m ON m.ID_MATRICULA = men.ID_MATRICULA
INNER JOIN Turma t ON t.ID_TURMA = m.ID_TURMA
INNER JOIN Modalidade md ON md.ID_MODALIDADE = t.ID_MODALIDADE;

ALTER TABLE Mensalidade
ALTER COLUMN VALOR DECIMAL(10,2) NOT NULL;